# Shepherd workspace directory
shpd_path=~/shpd
templates_path=${shpd_path}/templates
envs_path=${shpd_path}/envs

# Shepherd default environment type
default_env_type=docker-compose

# Logging Configuration
log_file=${shpd_path}/logs/shepctl.log
log_level=WARNING
log_stdout=false
log_format=%(asctime)s - %(levelname)s - %(message)s
